#!/usr/bin/env bash
# Sync VERSION into generated sources and docs (iOS).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"

if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-].+)?$ ]]; then
  echo "Invalid VERSION: '$VERSION'" >&2
  exit 1
fi

replace_in_file() {
  local file="$1"
  local expression="$2"
  if [[ ! -f "$file" ]]; then
    echo "Skip missing file: $file" >&2
    return 0
  fi
  sed -i.bak -E "$expression" "$file"
  rm -f "${file}.bak"
}

cat > "$ROOT/Sources/DivergeSDK/Version.swift" <<EOF
// Generated by scripts/sync-version.sh from VERSION. Do not edit by hand.
enum VersionInfo {
    static let current = "$VERSION"
}
EOF

replace_in_file "$ROOT/Docs/site/index.html" \
  "s/(docs scaffold · v)[0-9]+\\.[0-9]+\\.[0-9]+([.-][^<\"]*)?/\\1${VERSION}/"

replace_in_file "$ROOT/Docs/site/getting-started.html" \
  "s|(from: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")|\\1${VERSION}\\3|"

replace_in_file "$ROOT/README.md" \
  "s|(from: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")|\\1${VERSION}\\3|"

PBX="$ROOT/Samples/iOS/DivergeSample.xcodeproj/project.pbxproj"
if [[ -f "$PBX" ]]; then
  replace_in_file "$PBX" "s/MARKETING_VERSION = [^;]+;/MARKETING_VERSION = ${VERSION};/"
fi

YG="$ROOT/Samples/iOS/project.yml"
if [[ -f "$YG" ]]; then
  replace_in_file "$YG" "s/(MARKETING_VERSION: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")/\\1${VERSION}\\3/"
fi

echo "Synced version $VERSION"
