#!/usr/bin/env bash
# Sync VERSION into generated sources and docs (iOS).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-].+)?$ ]] || { echo "Invalid VERSION"; exit 1; }

replace_in_file() {
  local file="$1" expression="$2"
  [[ -f "$file" ]] || return 0
  sed -i.bak -E "$expression" "$file"
  rm -f "${file}.bak"
}

cat > "$ROOT/Sources/DivergeSDK/Version.swift" <<EOF
/// Generated by scripts/sync-version.sh from VERSION. Do not edit by hand.
enum VersionInfo {
    static let current = "$VERSION"
}
EOF

replace_in_file "$ROOT/Docs/site/index.html" \
  "s/(docs scaffold · v)[0-9]+\\.[0-9]+\\.[0-9]+([.-][^<\"]*)?/\\1${VERSION}/"
replace_in_file "$ROOT/Docs/site/getting-started.html" \
  "s|(from: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")|\\1${VERSION}\\3|"
replace_in_file "$ROOT/README.md" \
  "s|(from: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")|\\1${VERSION}\\3|"
replace_in_file "$ROOT/Samples/iOS/DivergeSample.xcodeproj/project.pbxproj" \
  "s/MARKETING_VERSION = [^;]+;/MARKETING_VERSION = ${VERSION};/"
replace_in_file "$ROOT/Samples/iOS/project.yml" \
  "s/(MARKETING_VERSION: \")[0-9]+\\.[0-9]+\\.[0-9]+([.-][^\"]*)?(\")/\\1${VERSION}\\3/"

echo "Synced version $VERSION"
